// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApNOXvc35bR00W7SMatMErRVWKNCISvUA',
    appId: '1:699912211932:web:227a6878d9cf6bfe7f9319',
    messagingSenderId: '699912211932',
    projectId: 'quiz-app-38459',
    authDomain: 'quiz-app-38459.firebaseapp.com',
    storageBucket: 'quiz-app-38459.appspot.com',
    measurementId: 'G-EVN5MLT5B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd4ljelTSIdoUagaBSG4vrM-rB6PT6SaM',
    appId: '1:699912211932:android:9433b97822802f8b7f9319',
    messagingSenderId: '699912211932',
    projectId: 'quiz-app-38459',
    storageBucket: 'quiz-app-38459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM6qu1r6gtWLj6WTZfqQ4nTidLozUGFBI',
    appId: '1:699912211932:ios:621c5cb6fea985d57f9319',
    messagingSenderId: '699912211932',
    projectId: 'quiz-app-38459',
    storageBucket: 'quiz-app-38459.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM6qu1r6gtWLj6WTZfqQ4nTidLozUGFBI',
    appId: '1:699912211932:ios:621c5cb6fea985d57f9319',
    messagingSenderId: '699912211932',
    projectId: 'quiz-app-38459',
    storageBucket: 'quiz-app-38459.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApNOXvc35bR00W7SMatMErRVWKNCISvUA',
    appId: '1:699912211932:web:e4cd766f5c89095b7f9319',
    messagingSenderId: '699912211932',
    projectId: 'quiz-app-38459',
    authDomain: 'quiz-app-38459.firebaseapp.com',
    storageBucket: 'quiz-app-38459.appspot.com',
    measurementId: 'G-3F90E3357H',
  );
}
